### ISSUE TITLE
Alert log not showing any data

### ISSUE THREAD

**Issue by kklemen** [johnsusek/praeco#155]
Alert log in praeco gui does not show any data for previous alert history.
Alerts were definitely sent out.

Praeco 14, elastic 7.1.1

**Comment by johnsusek** [comment]
Hello, is this still happening for you with the latest?

**Comment by kklemen** [comment]
hi John,

Updated to 1.1 with elastalert 7.3.2 on ubuntu. Still not showing any alerts sent.

**Comment by jfcantu** [comment]
I think this is an error in the Elastalert API code resulting from the [removal of mapping types in Elasticsearch 7.x.](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html)

It looks like the `metadata` handler for the alert logging writeback index specifically, is searching for documents with a `_type` of `elastalert`. Since 7.x, this returns no results, because all documents have a `_type` of `_doc`.

https://github.com/ServerCentral/elastalert-server/blob/0eadd13b1cac54af6d9bcc1c146957ee1f62c8db/src/handlers/metadata/get.js#L95

**Comment by jfcantu** [comment]
As well, should anyone want it that badly, I made a patched Docker image that addresses this in the meantime:

https://hub.docker.com/r/jfcantu/elastalert

**Comment by johnsusek** [comment]
Fixed in latest release
