### ISSUE TITLE
no alert with agg-max

### ISSUE THREAD

**Issue by StefanSa** [johnsusek/praeco#175]
Hi john,
Any idea why this rule does not apply, or does not generate an alarm ?
Test also generates no alarm.
![Alarms](https://user-images.githubusercontent.com/6105075/68490098-b1ac9580-0248-11ea-9a21-939c15e57e0e.png)

thx for your help here.

**Comment by janreges** [comment]
I have same issue. It doesn't work - alert/test alert are not triggered.

**Comment by daichi703n** [comment]
Hi, @StefanSa , @janreges 
Please let me know which version (Praeco, ElastAlert Server, ElastAlert) are you using? When I used latest version of each Docker Image (`servercentral/praeco`, `servercentral/elastalert`), standard function of alerting did NOT work because of ElastAlert's bug (Import does NOT work).

By using `elastalert.py` and `test_rule.py` from `Yelp/elastalert:master`, it works for me. (and disable uninstalled module ref: https://github.com/daichi703n/praeco/compare/50c85e0e9655a8dd75ed60193451c53e963a6587...1481254496fc7f9b8e10433c2c943218b827c97c )
![image](https://user-images.githubusercontent.com/22485636/74310925-a4f08e00-4db1-11ea-84c9-6e6946010ddc.png)
![image](https://user-images.githubusercontent.com/22485636/74311036-e5500c00-4db1-11ea-8b48-25ff25aaaa4e.png)

One more question. Are your other rules work properly? If not, firstly could you try very simple rule such as `WHEN count  GROUPED OVER source_node.host  UNFILTERED  IS NOT EMPTY`.
![image](https://user-images.githubusercontent.com/22485636/74311088-fc8ef980-4db1-11ea-8f3b-eb90a71f4ea7.png)

Regards

**Comment by johnsusek** [comment]
Please re-open this issue with your yaml file if you suspect this is a praeco issue, not an elastalert issue. Praeco simply created elastalert rules, so if alerting isn't working, we need to at least see the yaml file. 

Please see this section of the README: 

**I'm not receiving alerts even though I expect them**
First of all, try to test your alert with varying time frames and see if that is returning any results.

If the test is returning results, but you are not receiving any alerts, check the error log. There may be a problem with your alerter settings. Make sure you edited rules/BaseRule.config and have correct values in there.

If the test is not returning results, even though you think it should, try reading the elastalert docs for your rule type. Compare the yaml from praeco with the options from the docs to make sure the rule is being created as expected. If praeco is generating the wrong yaml, please file an issue.
