### ISSUE TITLE
WITH_OPTIONS: Use Count Query, Doc Type Detect Not Correct

### ISSUE THREAD

**Issue by jyj1993126** [johnsusek/praeco#180]
WITH_OPTIONS
Use Count Query

Doc types choices are not correct

**Comment by johnsusek** [comment]
What version of elasticsearch are you on? Can you elaborate a little on what doc_types you are supposed to be seeing, but arent? Thanks

**Comment by ricferr** [comment]
I also suffer from this behaviour.

Whenever i try to choose use_count, the doc_type dropdown shows these options:
![Screenshot_20200909_100130](https://user-images.githubusercontent.com/5982853/92578220-7c673e80-f283-11ea-8a4c-0906ddbb4e90.png)

I'm on Elasticsearch 7.6.

Shouldn't it atleast give me the _doc option ?

**Comment by altuhovsu** [comment]
Same here. We shoud see the _doc option.

**Comment by johnsusek** [comment]
Caused upstream by: https://github.com/Yelp/elastalert/issues/2424

**Comment by simonezambonim** [comment]
## Why can't we just type the `doc_type` in Praeco? 

Since it does not display the correct values  and I am obigated to give one, the standart would be "_doc",  why can't we gave a text field instead os a select_box for it?

This is an important issue because rules  like average, sum, min, max do NOT work (if OVER all documents).

**Comment by johnsusek** [comment]
@simonezambonim Good question, let's find the answer together!

The first thing I often do in this situation is search the repo for the area of the UI I am interested in, so we search for the label below the UI element:

https://github.com/johnsusek/praeco/search?q=Specify+the+_type+of+document+to+search+for

Now we've found the component in question, and here is where that label is:

https://github.com/johnsusek/praeco/blob/ba3757a88efa10df758d6728be887f27a919001e/src/components/config/ConfigCondition.vue#L716

We can see the UI element "el-select" inside "el-form-item" - let's search google to see what those are from: 

https://www.google.com/search?q=%22el-form-item%22%20%22el-select%22

Looks like a framework called "elementUI", so after googling that, we come across the docs for that framework & the select component:

https://element.eleme.io/#/en-US/component/select

Scrolling thru the various options, at the bottom there is a "create new items" section, which is exactly what we need! It looks like we simply add an `allow-create` attribute to the el-select component.

I *think* this should do what we want. I haven't tested this since I don't have a praeco or elastalert installation around. But I'll put a PR in, it can't hurt.

**Comment by johnsusek** [comment]
Change is in master - https://github.com/johnsusek/praeco/commit/57cefb5635299c5b7bd609725f134197aaa1e625

**Comment by simonezambonim** [comment]
Thanks @johnsusek! 
Your explanation was perfect! It gave me a good picture of how it works and how I may start helping the project.

Since I am using the docker version, I will probabilly  see this change in the next  build of the image and I will let you know if it worked!

PS.: I had no idea where to get started hahahaha! Thanks again for your time and your very detailed reply!
