### ISSUE TITLE
No graph and no OVER all documents

### ISSUE THREAD

**Issue by ValentinPifu** [johnsusek/praeco#335]
Hello,

With the last update the graph won't show anymore and I can't save OVER all documents, I can set OVER all documents but when I save it , it revert back.
I revert back to 1.8.2.

![Screenshot from 2021-03-23 12-31-23](https://user-images.githubusercontent.com/18114871/112132840-b8387480-8bd3-11eb-8850-1956f95647dc.png)

Thanks.

**Comment by nsano-rururu** [comment]
I can't because I'm busy. I'm sorry I'm going to sleep.

**Comment by nsano-rururu** [comment]
Close

**Comment by nsano-rururu** [comment]
1.8.4 released.(fix multiple query keys)
https://hub.docker.com/r/praecoapp/praeco

**Comment by nsano-rururu** [comment]
Close once. Please reopen if there is a problem.

**Comment by altuhovsu** [comment]
@nsano-rururu hello!  the graph won't show anymore if query key specified? Without query key I can see the graph
![image](https://user-images.githubusercontent.com/59618193/117970176-07c43280-b331-11eb-93fc-68eb4954c027.png)

**Comment by nsano-rururu** [comment]
That doesn't seem to be the case. Don't lie too much. Since there was a pattern that was specified and displayed, I think there are judgment conditions, but I can't understand until I check it. The logic for this process wasn't created by me

**Comment by nsano-rururu** [comment]
It may be a bug, but I don't know if it will be fixed soon. I'm not interested in Praeco anymore

**Comment by adrienyhuel** [comment]
@nsano-rururu the graph doesn't show, because the query fail in elasticsearch : 

{"error":{"name":"ResponseError","meta":{"body":{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:194] [terms] field doesn't support values of type: START_ARRAY"}],"type":"x_content_parse_exception","reason":"[1:194] [terms] field doesn't support values of type: START_ARRAY"},"status":400}

Query issued by Praeco looks like : 
"aggs":{"group_by_field":{"terms":{"field":["rawrequest.keyword"]},"aggs":{"by_minute"
It is constructed by Vue : https://github.com/johnsusek/praeco/blob/96c1e118aee483b7f44138b2f6f1f923d3fc3b9d/src/components/ESChart.vue#L325

"Group by field" comes from the query key and is now an array, but elasticsearch query cannot accpet an array in "group_by_field/terms/field"

**Comment by nsano-rururu** [comment]
@adrienyhuel 

Please make a pull request.
