### ISSUE TITLE
[elastalert-server/praeco]elasticsearch 8 support

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#441]
**elastalert-server**

- [x] Code fix due to callback-style api abolition
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/8.0/changelog-client.html

~praecoapp/elastalert-server:20220308~
praecoapp/elastalert-server:202200424

**praeco**

- [x] Graph is not displayed. ESChat.vue

- [x] The pull-down of the time field when creating a rule is frozen, and when it works, the following error message is displayed.
```
Get mapping failed. Make sure the index exists.
Could not fetch mappings.
```

**Comment by simonherbert** [comment]
I'm running Elasticsearch 7.17.1 and I'm getting these critical upgrade issues for 8.0:
`Convert [@timestamp] format [dateOptionalTime] which contains deprecated camel case to snake case. [dateOptionalTime] to [date_optional_time].`
.. for all praeco indices.

Stopping containers, deleting indices and starting again creates the @timestamp field with format `dateOptionalTime` instead of `date_optional_time` once again.

Using the latest docker images:
`praecoapp/elastalert-server:20220308`
`praecoapp/praeco:1.8.1`

**Comment by nsano-rururu** [comment]
@simonherbert 

Is there a problem with the operation? .. It is a warning that the specifications will change when the major version is upgraded by elasticsearch-py, so don't worry if you are using 7.x. When you raise it to es 8, once you delete the index of elastalert2, the index corresponding to the format in which the warning is issued will be created.

**Comment by nsano-rururu** [comment]
@simonherbert
https://github.com/jertel/elastalert2/tree/master/elastalert/es_mappings/8

**Comment by nsano-rururu** [comment]
@simonherbert 
Shouldn't I ask in the elastalert2 repository as it works with elastalert2?

**Comment by nsano-rururu** [comment]
@simonherbert 

This is a task issue so I didn't want you to write a question.

**Comment by simonherbert** [comment]
@nsano-rururu thanks for your answer, you're right. I removed the indices before upgrading to version 8, and it created them correctly afterwards.
Sorry for commenting on this issue, I should have created a new one.
