### ISSUE TITLE
Elastalert to TheHive.

### ISSUE THREAD

**Issue by sqrtZeroKnowledge** [johnsusek/praeco#489]
## 🐛 Elastalert to TheHive (Description)

Hello Team,

Please kindly I would like to send over elastalert and praeco to TheHive detailed description with the fields in the body text but not work for me at all is the declaration still missing for me, did is there any clear guide I cal apply for this? thanks.

Thanks

**Comment by nsano-rururu** [comment]
I haven't tried it because I don't have a hive environment.
Describe hive_connection settings in BaseRule.config.
Screen configurable some settings in hive_alert_config.
hive_observable_data_mapping is not supported.
I implemented it when I exchanged the following issue, and asked the person who made the inquiry at that time to check the operation.
https://github.com/johnsusek/praeco/issues/208

**Comment by nsano-rururu** [comment]
I wrote it in the readme. I completely forgot
https://github.com/johnsusek/praeco#how-to-setup-thehive

**Comment by sqrtZeroKnowledge** [comment]
Thanks for your hint it's really helpful now I integrated Elastalert with TheHive but seems like artifacts are not supported I'm now trying out a way to add the artifacts part hopefully not will cost me time.

**Comment by nsano-rururu** [comment]
elastalert2 should have changed the implementation of thehive from the original elastalert. If it doesn't work, I recommend asking in the elastalert2 discussions.

elastalert2 discussions
https://github.com/jertel/elastalert2/discussions
elastalert2 thehive document
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#thehive

**Comment by sqrtZeroKnowledge** [comment]
Well noted thanks.
Else i will add it from this repo and let you know about the update.

Best regards.
