### ISSUE TITLE
Improvement: auto completion when creating filters

### ISSUE THREAD

**Issue by andrewmeyer** [johnsusek/praeco#63]
If possible, please switch the drop down menu to an auto-completing menu (like how email bodies are composed)

When creating rules for firewalls, each firewall prepends the type to the field, creating a very large list of fields to select.

**Comment by johnsusek** [comment]
Update: this ends up being fairly difficult because the query builder dropdowns are from a 3rd party component. I am going to have to fork it, add the capability for a filterable/autocomplete dropdown for fields, then get a PR merged in upstream. Totally doable, just a tad time consuming. Upside is the upstream vue-query-builder project would benefit from this change too.

**Comment by johnsusek** [comment]
vue-query-builder is no longer being maintained, gonna close this issue as it's kind of out of scope of praeco itself. we might want to consider alternatives to vue-query-builder going forward, or use our own fork
